// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmSRyJEKj0awWwFX36wMHl-n7b_UXi9hg',
    appId: '1:58017344880:web:d43e2b975be0412610f3b5',
    messagingSenderId: '58017344880',
    projectId: 'mug-app-ac065',
    authDomain: 'mug-app-ac065.firebaseapp.com',
    storageBucket: 'mug-app-ac065.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG3vA2eIt1kL0tPqyqUjqqt0_RIJZhJWY',
    appId: '1:58017344880:android:37ff18ac2f0db83810f3b5',
    messagingSenderId: '58017344880',
    projectId: 'mug-app-ac065',
    storageBucket: 'mug-app-ac065.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNKo3jsWrbqXkDa3X6GQ4GFlWrGmqpTCo',
    appId: '1:58017344880:ios:19f914e3d61b0ad810f3b5',
    messagingSenderId: '58017344880',
    projectId: 'mug-app-ac065',
    storageBucket: 'mug-app-ac065.appspot.com',
    iosClientId: '58017344880-3hjgbl0bvv4c872h1ddcjbgur7quhgmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mugApp',
  );
}
// Import the functions you need from the SDKs you need
// import { initializeApp } from "firebase/app";
// // TODO: Add SDKs for Firebase products that you want to use
// // https://firebase.google.com/docs/web/setup#available-libraries

// // Your web app's Firebase configuration
// const firebaseConfig = {
//   apiKey: "AIzaSyCmSRyJEKj0awWwFX36wMHl-n7b_UXi9hg",
//   authDomain: "mug-app-ac065.firebaseapp.com",
//   projectId: "mug-app-ac065",
//   storageBucket: "mug-app-ac065.appspot.com",
//   messagingSenderId: "58017344880",
//   appId: "1:58017344880:web:897f74a78c389d0310f3b5"
// };

// // Initialize Firebase
// const app = initializeApp(firebaseConfig);